[backend.resourcehubservices]

# Database configuration

USER = "USER"
PASSWORD ="PASSWORD"
HOST = "localhost"
PORT = "PORT"
DATABASE = "DATABASE"

# SMTP server configuration

SMTP_HOST = "SMTP_HOST"
SMTP_USER = "SMTP_USER"
SMTP_PASSWORD = "SMTP_PASSWORD"

#API keys

PDFSHIFT_API_KEY = "PDFSHIFT_API_KEY"